src/views/alerts.py
from flask import Blueprint, redirect, render_template, request, url_for, session

from models.item import Item
from models.alert import Alert
from models.store import Store
from models.user.decorators import requires_login

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/', methods=['GET'])
@alert_blueprint.route('/all', methods=['GET'])
@requires_login
def all_alerts():
    if 'email' in session:
        alerts = Alert.find_many_by('user_id', session['user_id'])
        for alert in alerts:
            alert.item.load_price()
        return render_template('alerts/all_alerts.html', alerts=alerts)
    return "Please sign in."

@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        name = request.form['name']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])
        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query, name)
        item.load_price()
        item.save_to_mongo()
        Alert(price_limit, item._id, session['user_id']).save_to_mongo()
        return redirect(url_for('.all_alerts'))
    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit', methods=['GET'])
@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert is not None:
        if request.method == 'POST':
            new_price_limit = float(request.form['price_limit'])
            alert.price_limit = new_price_limit
            alert.save_to_mongo()
            return redirect(url_for('.all_alerts'))
        return render_template('alerts/edit_alert.html', alert=alert)
    else:
        return redirect(url_for('.all_alerts'))

@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    Alert.get_by_id(alert_id).remove_from_mongo()
    return redirect(url_for('.all_alerts'))

src/views/stores.py
import json
from flask import Blueprint, redirect, render_template, request, url_for

from models.store import Store
from models.user.decorators import requires_login

store_blueprint = Blueprint('stores', __name__)

@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_store():
    if request.method == 'POST':
        store = Store(name=request.form['store_name'],
                      url_prefix=request.form['url'],
                      tag_name=request.form['tag_name'],
                      query=json.loads(request.form['query']))
        if store:
            store.save_to_mongo()
    return render_template('stores/new_store.html')

@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_login
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if store is not None:
        if request.method == 'POST':
            new_url_prefix = request.form['url_prefix']
            new_tag_name = request.form['tag_name']
            new_query = request.form['query']
            store.url_prefix = new_url_prefix
            store.tag_name = new_tag_name
            store.query = new_query
            store.save_to_mongo()
            return redirect(url_for('.all_stores'))
        return render_template('stores/edit_store.html', store=store)
    else:
        return redirect(url_for('.all_stores'))

@store_blueprint.route('/delete/<string:store_id>')
@requires_login
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.all_stores'))

@store_blueprint.route('/', methods=['GET'])
@store_blueprint.route('/all', methods=['GET'])
@requires_login
def all_stores():
    stores = Store.all()
    return render_template('stores/all_stores.html', stores=stores)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">
        <title>Title</title>
    </head>
    <body>

        {% include 'navbar.html' %}

        <div class="container-fluid messages-group">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{category}}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <div class="content container-fluid body-group" style="display: flex; justify-content: center;">
            {% block content %}
            {% endblock %}
        </div>
        <div class="container-fluid footer-group">
            {% include 'footer.html' %}
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

src/templates/navbar.html
<div class="container-fluid">
    <header class="navbar navbar-expand-sm navbar-dark bg-dark mb-2 bd-navbar">
        <a class="navbar-brand" href='/'>EyePrice</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" 
                aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavAltMarkup" class="collapse navbar-collapse">
            <div class="navbar-nav-scroll">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown m-2">
                        <button class="btn btn-dark" type="button" href="{{ url_for('stores.all_stores')}}">Stores</button>
                        <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu dropdown-menu-left dropdown-menu-sm-right">
                            <a class="dropdown-item" href="{{ url_for('stores.new_store') }}">New Store</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('stores.all_stores') }}">Browse All</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown m-2">
                        <button class="btn btn-dark" type="button" href="{{ url_for('alerts.all_alerts')}}">Alerts</button>
                        <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu dropdown-menu-lg-left">
                            <a class="dropdown-item" href="{{ url_for('alerts.new_alert') }}">New Alert</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('alerts.all_alerts') }}">Browse All</a>
                        </div>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav mb-2 ml-2">
                <li class="nav-item">
                    <a class="nav-link" href="/users/logout">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/users/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/users/register">Register</a>
                </li>
            </ul>
        </div>
    </header>
</div>

src/templates/new_item.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Add New Product</h1></header>
    <section class="new-item-form">
        <form method="post">
            <div>
                <label for="url">URL</label>
                <input type="text" id="url" name="url"
                       placeholder="https://..." aria-describedby="urlHelp"/>
                <small id="urlHelp">
                    Enter full URL for the website item.
                </small>
            </div>
            <div>
                <label for="tag_name">Tag name</label>
                <input type="text" id="tag_name" name="tag_name"
                       placeholder="span" aria-describedby="tagNameHelp"/>
                <small id="tagNameHelp">
                    Enter HTML tag name for the website item's price.
                </small>
            </div>
            <div>
                <label for="query">Query</label>
                <input type="text" id="query" name="query"
                       placeholder='{"id": "..."}' aria-describedby="queryHelp"/>
                <small id="queryHelp">
                    Enter full id found in the HTML tag for the website item's price.
                </small>
            </div>
            <button type="submit">Create</button>
        </form>

    </section>

{% endblock %}

src/templates/new_steam_item.html
{% extends "base.html" %}

{% block content %}

    <header><h1>Add Item from Steam Product</h1></header>
    <section class="new-item-steam-form">
        <form method="post">
            <div>
                <label for="url">URL</label>
                <input type="text" id="url" name="url"
                       placeholder="https://..." aria-describedby="urlHelp"/>
                <small id="urlHelp">
                    Enter full URL for the website item.
                </small>
                <button type="submit">Create</button>
            </div>
        </form>

    </section>

{% endblock %}