src/models/alert.py
from dataclasses import dataclass, field
from typing import Dict
from uuid import uuid4

from models.model import Model
from models.item import Item
from models.user import User
from libs.mailgun import Mailgun 

@dataclass(eq=False)
class Alert(Model):
    collection: str = field(default='alerts', init=False)
    price_limit: float
    item_id: str
    user_id: str
    _id: str = field(default_factory=lambda: uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)

    def json(self) -> Dict:
        return {
            'price_limit': self.price_limit,
            'item_id': self.item_id,
            'user_id': self.user_id,
            '_id': self._id
        }

    def notify_price_reached(self) -> None:
        self.item.load_price()
        if self.item.price < self.price_limit:
            Mailgun.send_email(
                user_email=User.get_by_id(self.user_id).email,
                subject=f"Sale for item: {self.item.name}",
                text=f"Your item '{self.item.name}' has reached a price below {self.price_limit}! Latest price is {self.item.price}. Click {self.item.url} to visit item page.",
                html=f"<p>Your alert {self.item.name} has triggered and the item is priced under: {self.price_limit}.</p><p>The latest price is {self.item.price}. Visit item page <a href={self.item.url}>here</a>.</p> ")

src/views/alerts.py
from flask import Blueprint, redirect, render_template, request, url_for, session

from models.item import Item
from models.alert import Alert
from models.store import Store
from models.user.decorators import requires_login

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/', methods=['GET'])
@alert_blueprint.route('/all', methods=['GET'])
@requires_login
def all_alerts():
    if 'email' in session:
        alerts = Alert.find_many_by('user_id', session['user_id'])
        for alert in alerts:
            alert.item.load_price()
        return render_template('alerts/all_alerts.html', alerts=alerts)
    return "Please sign in."

@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        name = request.form['name']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])
        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query, name)
        item.load_price()
        item.save_to_mongo()
        Alert(price_limit, item._id, session['user_id']).save_to_mongo()
        return redirect(url_for('.all_alerts'))
    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit', methods=['GET'])
@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert is not None:
        if request.method == 'POST':
            new_price_limit = float(request.form['price_limit'])
            alert.price_limit = new_price_limit
            alert.save_to_mongo()
            return redirect(url_for('.all_alerts'))
        return render_template('alerts/edit_alert.html', alert=alert)
    else:
        return redirect(url_for('.all_alerts'))

@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    Alert.get_by_id(alert_id).remove_from_mongo()
    return redirect(url_for('.all_alerts'))

src/templates/alerts/all_alerts.html
{% extends "base.html" %}

{% block content %}

<section class="all-alerts-list">
    <h1>All Alerts Saved</h1>
    <ul class="list-group mb-3" style="list-style-type:none;">
        <div>
            {% for alert in alerts %}
                <li class="list-group-alert mb-2">
                    <div class="card list-group-item" style="width: 20rem;">
                        <h4 class="card-title alert-item-id mb-3">{{ alert.item.name }}</h4>
                        <h6>Item Most Recent Price</h6>
                        <p class="card-text">{{ alert.item.price }}</p>
                        <h6>Alert Price Limit</h6>
                        <p class="card-text" id="alert-price-limit">{{ alert.price_limit }}</p>
                        <div class="btn-toolbar" style="display: flex; justify-content:center;">
                            <a class="btn btn-success mr-2" href="{{ alert.item.url }}">
                                View
                            </a>
                            <a class="btn btn-primary mr-2" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">
                                Edit
                            </a>
                            <a class="btn btn-danger mr-2" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">
                                Delete
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </div>
    </ul>
</section>

{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}

<section class="edit-alert-form">
    <h1>Edit Alert</h1>
    <form method="post">
        <div class="form-group">
            <label for="name">Alert Name</label>
            <input type="text" class="form-control" id="name" name="name"
                   placeholder="{{ alert.item.name }}" aria-describedby="NameHelp" disabled>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url"
                   placeholder="{{ alert.item.url }}" aria-describedby="itemUrlHelp" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Price Limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit"
                   placeholder="{{ alert.price_limit }}" value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp"/>
            <small class="form-text text-muted" id="priceLimitHelp">
                Edit to set a new price limit for this Alert.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a class="btn btn-danger" href="{{ url_for('alerts.all_alerts') }}">Cancel</a>
    </form>
</section>


{% endblock %}

src/templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}

<section class="new-alert-form">
    <h1>Add New Alert for Product</h1>
    <form method="post">
        <div class="form-group">
            <label for="name">Name for Item Alert</label>
            <input type="text" class="form-control" id="name" name="name"
                   placeholder="Name" aria-describedby="NameHelp">
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url"
                   placeholder="https://..." aria-describedby="itemUrlHelp">
        </div>
        <div class="form-group">
            <label for="price_limit">Price Limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit"
                   placeholder="0.00" aria-describedby="priceLimitHelp"/>
            <small class="form-text text-muted" id="priceLimitHelp">
                Enter a price limit for the item.
            </small>
        </div>
        <button type="submit" class="btn btn-primary" >Create</button>
    </form>
</section>

{% endblock %}