src/models/store.py
from dataclasses import dataclass, field
from typing import Dict
from uuid import uuid4
import re

from models.model import Model

@dataclass(eq=False)
class Store(Model):
    collection: str = field(default='stores', init=False)
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid4().hex)

    def json(self) -> Dict:
        return {
            'name': self.name,
            'url_prefix': self.url_prefix,
            'tag_name': self.tag_name,
            'query': self.query,
            '_id': self._id
        }

    @classmethod
    def get_by_name(cls, store_name: str) -> "Store":
        return cls.find_one_by('name', store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> "Store":
        url_regex = {"$regex": "^{}".format(url_prefix)}
        return cls.find_one_by('url_prefix', url_regex)

    @classmethod
    def find_by_url(cls, url: str) -> "Store":
        """
        Return Store object for the given url. Ex) "https://store.steampowered.com/app/1241700/"
        :param url:     The item's url
        :return:        a Store object
        """
        pattern = re.compile(r"(https?://.*?/)")
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

src/views/stores.py
import json
from flask import Blueprint, redirect, render_template, request, url_for

from models.store import Store
from models.user.decorators import requires_login

store_blueprint = Blueprint('stores', __name__)

@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_store():
    if request.method == 'POST':
        store = Store(name=request.form['store_name'],
                      url_prefix=request.form['url'],
                      tag_name=request.form['tag_name'],
                      query=json.loads(request.form['query']))
        if store:
            store.save_to_mongo()
    return render_template('stores/new_store.html')

@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_login
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if store is not None:
        if request.method == 'POST':
            new_url_prefix = request.form['url_prefix']
            new_tag_name = request.form['tag_name']
            new_query = request.form['query']
            store.url_prefix = new_url_prefix
            store.tag_name = new_tag_name
            store.query = new_query
            store.save_to_mongo()
            return redirect(url_for('.all_stores'))
        return render_template('stores/edit_store.html', store=store)
    else:
        return redirect(url_for('.all_stores'))

@store_blueprint.route('/delete/<string:store_id>')
@requires_login
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.all_stores'))

@store_blueprint.route('/', methods=['GET'])
@store_blueprint.route('/all', methods=['GET'])
@requires_login
def all_stores():
    stores = Store.all()
    return render_template('stores/all_stores.html', stores=stores)

src/templates/stores/all_stores.html
{% extends "base.html" %}

{% block content %}

<section class="all-stores-list">
    <h1>All Stores Saved</h1>
    <ul class="list-group mb-3" style="list-style-type:none;">
        <div>
            {% for store in stores %}
                <li class="list-group-alert mb-2">
                    <div class="card list-group-item" style="width: 20rem;">
                        <h3 class="card-title alert-item-id mb-3">
                            <a href="{{ store.url_prefix }}">
                                {{ store.name }}
                            </a>
                        </h3>
                        <h5>Store Root URL</h5>
                        <p class="card-text">{{ store.url_prefix }}</p>
                        <h5>Store Tag Name</h5>
                        <p class="card-text">{{ store.tag_name }}</p>
                        <h5>Store Query .json</h5>
                        <p class="card-text">{{ store.query }}</p>
                        <div class="btn-toolbar" style="display: flex; justify-content:center;">
                            <a class="btn btn-success mr-2" href="{{ store.url_prefix }}">
                                Visit
                            </a>
                            <a class="btn btn-primary mr-2"
                               href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                                Edit
                            </a>
                            <a class="btn btn-danger mr-2" href="{{ url_for('stores.delete_store', store_id=store._id) }}">
                                Delete
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </div>
    </ul>
</section>

{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}

<section class="new-store-form">
    <h1>Edit {{ store.name }} Store</h1>
    <form method="post">
        <div class="form-group">
            <label for="store_name">Store Name</label>
            <input type="text" class="form-control" id="store_name" name="store_name"
                   placeholder="{{ store.name }}" aria-describedby="storeNameHelp" disabled/>
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url"
                   placeholder="{{ store.url_prefix }}" value="{{ store.url_prefix }}" aria-describedby="urlHelp"/>
            <small class="form-text text-muted" id="urlHelp">
                Enter the full URL for the website.
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name"
                   placeholder="{{ store.tag_name }}" aria-describedby="tagNameHelp"/>
            <small class="form-text text-muted" id="tagNameHelp">
                Enter HTML tag name for the website item's price.
            </small>
        </div>
        <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query"
                   placeholder='{{ store.query }}' aria-describedby="queryHelp"/>
            <small class="form-text text-muted" id="queryHelp">
                Enter id in .json form found in the HTML tag for the website item's price.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a class="btn btn-danger" href="{{ url_for('stores.all_stores') }}">Cancel</a>
    </form>

</section>

{% endblock %}

src/templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}

<section class="new-store-form">
    <h1>Add New Store</h1>
    <form method="post">
        <div class="form-group">
            <label for="store_name">Store Name</label>
            <input type="text" class="form-control" id="store_name" name="store_name"
                   placeholder="Store Name" aria-describedby="storeNameHelp"/>
            <small class="form-text text-muted" id="storeNameHelp">
                Enter name to refer to for the store.
            </small>
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url"
                   placeholder="https://www.example.com/" aria-describedby="urlHelp"/>
            <small class="form-text text-muted" id="urlHelp">
                Enter the full URL for the website.
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name"
                   placeholder="span" aria-describedby="tagNameHelp"/>
            <small class="form-text text-muted" id="tagNameHelp">
                Enter HTML tag name for the website item's price.
            </small>
        </div>
        <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query"
                   placeholder='{"id": "..."}' aria-describedby="queryHelp"/>
            <small class="form-text text-muted" id="queryHelp">
                Enter id in .json form found in the HTML tag for the website item's price.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

</section>

{% endblock %}